/**
 * =============================================================================
 * EVENT ENTITY
 * =============================================================================
 * 
 * Represents an analytics event (page view, button click, etc.)
 * 
 * TABLE: events
 * 
 * This is the main data table - every tracked action becomes a row here.
 * The schema is designed to:
 * - Support PostgreSQL now
 * - Migrate to ClickHouse later (compatible column types)
 * 
 * INDEXES:
 * -------
 * Indexes speed up queries by creating sorted data structures.
 * We index the columns we query most often:
 * - (tenantId, timestamp): Dashboard queries by date range
 * - (sessionId): Looking up events for a session
 * - (eventName, timestamp): Funnel analysis
 */

import {
  Entity,
  Column,
  PrimaryColumn,
  CreateDateColumn,
  Index,
} from 'typeorm';

/**
 * @Entity('events') - Maps this class to the 'events' table.
 * 
 * @Index(['tenantId', 'timestamp']) - Composite index on (tenant_id, timestamp).
 * Used by: Dashboard queries, funnel analysis
 * 
 * @Index(['sessionId']) - Index on session_id.
 * Used by: Session detail view, event timeline
 * 
 * @Index(['eventName', 'timestamp']) - Composite index on (event_name, timestamp).
 * Used by: Funnel step counting
 */
@Entity('events')
@Index(['tenantId', 'timestamp'])
@Index(['sessionId'])
@Index(['eventName', 'timestamp'])
export class EventEntity {
  /**
   * Primary key - UUID generated by the SDK.
   * 
   * @PrimaryColumn('uuid') - Primary key of type UUID.
   * Unlike @PrimaryGeneratedColumn(), we provide our own value.
   */
  @PrimaryColumn('uuid')
  eventId: string;

  /**
   * Unique message ID for deduplication.
   * If network issues cause duplicate sends, we can detect them.
   */
  @Column('uuid', { unique: true })
  messageId: string;

  // =========================================================================
  // TENANT/PROJECT (Multi-tenancy support)
  // =========================================================================

  /**
   * Tenant (organization) ID.
   * All queries should filter by tenantId to ensure data isolation.
   */
  @Column({ length: 50 })
  tenantId: string;

  /**
   * Project ID within the tenant.
   * A tenant can have multiple projects (e.g., staging, production).
   */
  @Column({ length: 50 })
  projectId: string;

  // =========================================================================
  // EVENT INFO
  // =========================================================================

  /**
   * Name of the event (e.g., 'page_view', 'button_click', 'return_filed').
   */
  @Column({ length: 100 })
  eventName: string;

  /**
   * Type of event: 'page', 'track', 'identify'.
   * Default is 'track' for custom events.
   */
  @Column({ length: 20, default: 'track' })
  eventType: string;

  /**
   * When the event occurred (client-side timestamp).
   * 
   * 'timestamptz' = timestamp with time zone in PostgreSQL.
   * Always store times in UTC!
   */
  @Column('timestamptz')
  timestamp: Date;

  /**
   * When the server received the event.
   * 
   * @CreateDateColumn - TypeORM sets this automatically on insert.
   */
  @CreateDateColumn({ type: 'timestamptz' })
  receivedAt: Date;

  // =========================================================================
  // IDENTITY
  // =========================================================================

  /**
   * Anonymous ID - persistent UUID stored in browser.
   * Tracks a device/browser across sessions.
   */
  @Column({ length: 100 })
  anonymousId: string;

  /**
   * User ID - set after login/identification.
   * Nullable because not all events have an identified user.
   */
  @Column({ type: 'varchar', length: 100, nullable: true })
  userId: string | null;

  /**
   * Session ID - groups events within a visit.
   * Reset after 30 minutes of inactivity or campaign change.
   */
  @Column({ length: 100 })
  sessionId: string;

  // =========================================================================
  // CHANNEL (Phase 2 preparation)
  // =========================================================================

  /**
   * Channel type: 'web', 'whatsapp', 'mobile'.
   * Phase 1 is web-only, but the schema supports future channels.
   */
  @Column({ length: 20, default: 'web' })
  channelType: string;

  /**
   * External ID (e.g., WhatsApp phone number).
   * For future cross-channel tracking.
   */
  @Column({ type: 'varchar', length: 100, nullable: true })
  externalId: string | null;

  /**
   * Handshake token for cross-channel identity.
   * When a user moves from WhatsApp to web, this links their sessions.
   */
  @Column({ type: 'varchar', length: 100, nullable: true })
  handshakeToken: string | null;

  // =========================================================================
  // PAGE CONTEXT
  // =========================================================================

  /** Page path (e.g., '/mri/validation') */
  @Column({ type: 'varchar', length: 500, nullable: true })
  pagePath: string | null;

  /** Full page URL */
  @Column('text', { nullable: true })
  pageUrl: string | null;

  /** Page title */
  @Column({ type: 'varchar', length: 500, nullable: true })
  pageTitle: string | null;

  /** Referring page URL */
  @Column('text', { nullable: true })
  pageReferrer: string | null;

  // =========================================================================
  // DEVICE INFO (Enriched by processor)
  // =========================================================================

  /** Raw User-Agent string */
  @Column('text', { nullable: true })
  userAgent: string | null;

  /** Device type: 'desktop', 'mobile', 'tablet' */
  @Column({ type: 'varchar', length: 20, nullable: true })
  deviceType: string | null;

  /** Operating system name */
  @Column({ type: 'varchar', length: 50, nullable: true })
  osName: string | null;

  /** Operating system version */
  @Column({ type: 'varchar', length: 50, nullable: true })
  osVersion: string | null;

  /** Browser name */
  @Column({ type: 'varchar', length: 50, nullable: true })
  browserName: string | null;

  /** Browser version */
  @Column({ type: 'varchar', length: 50, nullable: true })
  browserVersion: string | null;

  // =========================================================================
  // GEO INFO (Enriched by processor)
  // =========================================================================

  /**
   * IP address - stored for geo-lookup.
   * 
   * 'inet' is PostgreSQL's IP address type.
   * Consider privacy: you may want to anonymize or delete IPs.
   */
  @Column('inet', { nullable: true })
  ipAddress: string | null;

  /** Two-letter country code (e.g., 'KE' for Kenya) */
  @Column({ type: 'varchar', length: 2, nullable: true })
  countryCode: string | null;

  /** City name */
  @Column({ type: 'varchar', length: 100, nullable: true })
  city: string | null;

  // =========================================================================
  // CUSTOM PROPERTIES
  // =========================================================================

  /**
   * Flexible JSON object for event-specific properties.
   * 
   * 'jsonb' is PostgreSQL's efficient JSON type.
   * Example: { "return_type": "mri", "amount": 5000 }
   */
  @Column('jsonb', { nullable: true })
  properties: Record<string, unknown> | null;

  // =========================================================================
  // METADATA
  // =========================================================================

  /** SDK version that sent this event */
  @Column({ type: 'varchar', length: 20, nullable: true })
  sdkVersion: string | null;

  /** When the processor fully processed this event */
  @Column('timestamptz', { nullable: true })
  processedAt: Date | null;
}
