/**
 * =============================================================================
 * SESSION ENTITY
 * =============================================================================
 * 
 * Represents a user session (a single visit to the application).
 * 
 * TABLE: sessions
 * 
 * WHAT IS A SESSION?
 * -----------------
 * A session groups all events from one "visit". It's bounded by:
 * - 30 minutes of inactivity (user stops browsing)
 * - Campaign change (clicked a new ad/link)
 * - Midnight (new day = new session)
 * 
 * WHY TRACK SESSIONS?
 * ------------------
 * - User journeys: "What did this user do during their visit?"
 * - Engagement: "How long do people spend on our site?"
 * - Conversion: "Did this session result in a return filed?"
 * 
 * SESSION AGGREGATES:
 * ------------------
 * This table stores pre-calculated aggregates (eventCount, pageCount)
 * for faster dashboard queries. Updated by the processor.
 */

import {
  Entity,
  Column,
  PrimaryColumn,
  Index,
} from 'typeorm';

@Entity('sessions')
@Index(['tenantId', 'startedAt'])
@Index(['userId'])
export class SessionEntity {
  /** Session ID (UUID) - generated by the SDK */
  @PrimaryColumn('uuid')
  sessionId: string;

  /** Tenant ID for multi-tenancy */
  @Column({ length: 50 })
  tenantId: string;

  /** Anonymous ID that started this session */
  @Column({ length: 100 })
  anonymousId: string;

  /** User ID if identified during this session */
  @Column({ type: 'varchar', length: 100, nullable: true })
  userId: string | null;

  // =========================================================================
  // TIMING
  // =========================================================================

  /** When the session started (first event) */
  @Column('timestamptz')
  startedAt: Date;

  /** When the session ended (last event before timeout) */
  @Column('timestamptz', { nullable: true })
  endedAt: Date | null;

  /** Session duration in seconds (computed) */
  @Column('int', { default: 0 })
  durationSeconds: number;

  // =========================================================================
  // METRICS (Pre-aggregated for fast queries)
  // =========================================================================

  /** Number of events in this session */
  @Column('smallint', { default: 0 })
  eventCount: number;

  /** Number of page views in this session */
  @Column('smallint', { default: 0 })
  pageCount: number;

  // =========================================================================
  // FIRST TOUCH (Attribution)
  // =========================================================================

  /** First page the user landed on */
  @Column({ type: 'varchar', length: 500, nullable: true })
  entryPage: string | null;

  /** Where the user came from (referrer) */
  @Column('text', { nullable: true })
  referrer: string | null;

  /** UTM Source (e.g., 'google', 'facebook') */
  @Column({ type: 'varchar', length: 100, nullable: true })
  utmSource: string | null;

  /** UTM Medium (e.g., 'cpc', 'email') */
  @Column({ type: 'varchar', length: 100, nullable: true })
  utmMedium: string | null;

  /** UTM Campaign (e.g., 'spring_sale') */
  @Column({ type: 'varchar', length: 100, nullable: true })
  utmCampaign: string | null;

  // =========================================================================
  // DEVICE
  // =========================================================================

  /** Device type used for this session */
  @Column({ type: 'varchar', length: 20, nullable: true })
  deviceType: string | null;

  /** Country where session originated */
  @Column({ type: 'varchar', length: 2, nullable: true })
  countryCode: string | null;

  // =========================================================================
  // OUTCOME
  // =========================================================================

  /** Did this session result in a conversion? */
  @Column({ default: false })
  converted: boolean;

  /** Which event was the conversion (e.g., 'return_filed') */
  @Column({ type: 'varchar', length: 100, nullable: true })
  conversionEvent: string | null;
}
