import { DataSource } from "typeorm";
import * as dotenv from "dotenv";
import { expand } from "dotenv-expand";
import {
  UserEntity,
  EventEntity,
  ContactSegmentEntity,
  SessionEntity,
  IdentityEntity,
  ProjectEntity,
  TenantEntity,
  TenantMembershipEntity,
  CrmIntegrationEntity,
  ApiKeyEntity,
  InvitationEntity,
  AgentProfileEntity,
  TeamEntity,
  TeamMemberEntity,
  InboxSessionEntity,
  MessageEntity,
  ResolutionEntity,
  ShiftEntity,
  AssignmentConfigEntity,
  RolePermissionEntity,
  RoleEntity,
  ContactEntity,
  ContactNoteEntity,
  AgentSessionEntity,
  AuditLogEntity,
  TwoFaVerificationEntity,
  PasswordResetTokenEntity,
  CampaignEntity,
  CampaignMessageEntity,
  CampaignScheduleEntity,
  EosEvent,
  EosTicketType,
  EosTicket,
  EosExhibitor,
  EosLead,
  Payment,
  GeneratedCard,
} from "./entities";
import { UserSessionEntity } from "./entities/user-session.entity";
import { SessionTakeoverRequestEntity } from "./entities/session-takeover-request.entity";

// Load environment variables
const env = dotenv.config({ path: ".env" });
expand(env);

export const AppDataSource = new DataSource({
  type: "postgres",
  host: process.env.DB_HOST || "localhost",
  port: parseInt(process.env.DB_PORT || "5432", 10),
  username: process.env.DB_USERNAME || "postgres",
  password: process.env.DB_PASSWORD || "postgres",
  database: process.env.DB_DATABASE || "analytics",
  entities: [
    UserEntity,
    EventEntity,
    SessionEntity,
    IdentityEntity,
    ProjectEntity,
    TenantEntity,
    TenantMembershipEntity,
    CrmIntegrationEntity,
    ApiKeyEntity,
    InvitationEntity,
    AgentProfileEntity,
    TeamEntity,
    TeamMemberEntity,
    InboxSessionEntity,
    MessageEntity,
    ResolutionEntity,
    ShiftEntity,
    AssignmentConfigEntity,
    RolePermissionEntity,
    RoleEntity,
    ContactEntity,
    ContactNoteEntity,
    AgentSessionEntity,
    AuditLogEntity,
    TwoFaVerificationEntity,
    PasswordResetTokenEntity,
    UserSessionEntity,
    SessionTakeoverRequestEntity,
    CampaignEntity,
    ContactSegmentEntity,
    CampaignMessageEntity,
    CampaignScheduleEntity,
    EosEvent,
    EosTicketType,
    EosTicket,
    EosExhibitor,
    EosLead,
    Payment,
    GeneratedCard,
  ],
  migrations: [
    "libs/database/migrations/*.ts",
    "libs/database/src/migrations/*.ts",
  ],
  synchronize: false,
});
